spring.application.name=carclient
server.port=8081

# SOAP paslaugos adresai (veikiančiam carserver projektui)
carclient.soap.wsdl-url=http://localhost:8080/services/cars?wsdl
carclient.soap.namespace=http://ws.carserver.kskrebe.eif.viko.lt/
carclient.soap.service-name=CarService
carclient.soap.port-name=CarPort

# Katalogas sugeneruotiems failams
carclient.output-dir=output
